version: '2'

services:
  mediaservices:
    image: mediaservices
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: always
    build: .
    ports:
      - 7000:7000
      - 9091:9091
    network_mode: bridge
    dns:
      - 1.1.1.1
      - 1.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /your/storage/transmission/path/:/data
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_USERNAME=username
      - OPENVPN_PASSWORD=password
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=192.168.1.0/24
